searchable:
  yt: https://www.youtube.com/results?search_query=___MSG___
  xv: http://www.xvideos.com/?k=___MSG___
  yp: https://www.youporn.com/search/?query=___MSG___
  dicofr: https://fr.wiktionary.org/wiki/___MSG___
  paste: pastebin.com/search?ie=UTF-8&q=___MSG___
  gh: https://github.com/search?q=___MSG___&type=Code&utf8=%E2%9C%93
  gl: https://gitlab.com/search?utf8=%E2%9C%93&search=___MSG___
  code: http://rosettacode.org/mw/index.php?search=___MSG___&title=Special%3ASearch
  cpp: http://www.cplusplus.com/search.do?q=___MSG___
  rb: ruby-doc.com/search.html?q=___MSG___&sa=Search
  ror: https://github.com/rails?utf8=%E2%9C%93&query=___MSG___
  php: https://php.net/manual-lookup.php?pattern=___MSG___
  python: https://www.python.org/search/?q=___MSG___
  archfr: https://wiki.archlinux.fr/index.php?title=Sp%C3%A9cial%3ARecherche&search=___MSG___
  arch: https://wiki.archlinux.org/index.php?title=Special%3ASearch&search=___MSG___&go=Go
  map: https://www.google.fr/maps/search/___MSG___
  actu: https://www.google.fr/search?hl=fr&gl=fr&tbm=nws&authuser=0&q=___MSG___
  news: https://www.google.fr/search?hl=fr&gl=fr&tbm=nws&authuser=0&q=___MSG___
  tw: https://twitter.com/search?q=___MSG___
  w: https://en.wikipedia.org/wiki/Special:Search?&go=Go&search=___MSG___
  wfr: https://fr.wikipedia.org/wiki/Special:Search?search=___MSG___&go=Go
  ddg: https://duckduckgo.com/?q=___MSG___
  g: https://encrypted.google.com/search?hl=en&q=___MSG___
  lmsfy: http://lmgtfy.com/?q=___MSG___
  search: http://lmgtfy.com/?q=___MSG___
  s: http://lmgtfy.com/?q=___MSG___
  buy: http://www.ebay.com/sch/i.html?_from=R40&_trksid=m570.l1313&_nkw=___MSG___&_sacat=0
  amazon: http://www.amazon.fr/s?url=search-alias=aps&field-keywords=___MSG___&tag=a2appw-21
  pkmn: http://pokemondb.net/search?q=___MSG___
  tek: https://intra.epitech.eu/user/___MSG___

base:
  enabled: true
  help_wait_duration: 120

network:
  duration: 2s
  wait: 5s      # Can be in ms or s

intranet:
  enabled: true

network:
  enabled: true
  dos_wait: 5s
  dos_duration: 3s
  trace_duration_init: 0.3s
  trace_duration_incr: 0.1s

coupons:
  enabled: true
  display_coupons: true

proxy:
  enable: true
  ip_addr: localhost
  ip_port: 0
  limit_users: 4
  passwd_file: /tmp/squid3_passwords

epitech:
  enable: true
  asteks:
    - "Faut surtout pas lock les mutexes !!! oO Après tu peux deadlock !"
    - "J'ai ubuntu pourquoi ?"
    - "C'est l'histoire d'un astek qui voulait installer Archlinux..."
    - "Ouais nan mais système unix avancé c'est chiant, ça sert à rien en fait..."

iamalive:
  enable: false
  database_file: plugins/iamalive.database.yaml

example:
  enabled: false