search_engines:
  ddg: https://duckduckgo.com/?q=___MSG___
  yt: https://www.youtube.com/results?search_query=___MSG___
  yp: https://www.youporn.com/search/?query=___MSG___
  gh: https://github.com/search?q=___MSG___&type=Code&utf8=%E2%9C%93
  w: https://en.wikipedia.org/wiki/Special:Search?&go=Go&search=___MSG___
  wfr: https://fr.wikipedia.org/wiki/Special:Search?search=___MSG___&go=Go
  tek: https://intra.epitech.eu/user/___MSG___
  archfr: https://wiki.archlinux.fr/index.php?title=Sp%C3%A9cial%3ARecherche&search=___MSG___
  arch: https://wiki.archlinux.org/index.php?title=Special%3ASearch&search=___MSG___&go=Go
  gl: https://gitlab.com/search?utf8=%E2%9C%93&search=___MSG___&group_id=&repository_ref=
  map: https://www.google.fr/maps/search/___MSG___/
  actu: https://www.google.fr/search?hl=fr&gl=fr&tbm=nws&authuser=0&q=___MSG___
  news: https://www.google.fr/search?hl=fr&gl=fr&tbm=nws&authuser=0&q=___MSG___
  tw: https://twitter.com/search?q=___MSG___
  buy: http://www.ebay.com/sch/i.html?_from=R40&_trksid=m570.l1313&_nkw=___MSG___&_sacat=0
  g: https://encrypted.google.com/search?hl=en&q=___MSG___
  code: http://rosettacode.org/mw/index.php?search=___MSG___&title=Special%3ASearch
  cpp: http://www.cplusplus.com/search.do?q=___MSG___
  xv: http://www.xvideos.com/?k=___MSG___
  amazon: http://www.amazon.fr/s?url=search-alias=aps&field-keywords=___MSG___&tag=a2appw-21
  pkmn: http://pokemondb.net/search?q=___MSG___
  rb: ruby-doc.com/search.html?q=___MSG___&sa=Search
  ror: https://github.com/rails?utf8=%E2%9C%93&query=___MSG___
